project:
  name: ccoa
  regions:
    - us-east-1
    - us-east-2
tests:
  lesson2-cfn-nag-pipeline:
    template: ./lesson2-preventive/cfn-nag-pipeline.yml
     # Create buildspec.yml, cfn-nag-pipeline.yml, volume.yml and zip to ccoa-workshop/2
     parameters:
       CodeCommitS3Bucket: 'ccoa-workshop'
       CodeCommitS3Key: '2/ccoa-2-examples.zip'