project:
  name: ccoa
  regions:
    - us-east-1
    - us-east-2
tests:
  lesson1-sqs:
    template: ./lesson1-automation/ccoa-1-cfn.yml
  # lesson2-cfn-nag:
  #   parameters:
  #     CodeCommitS3Key: "2/ccoa-2-examples.zip"
  #   template: ./lesson2-preventive/cfn-nag-pipeline.yml
  lesson1-sqs:
    template: ./lesson1-automation/ccoa-1-cfn.yml