project:
  name: ccoa
  regions:
    - us-east-1
    - us-east-2
tests:
  lesson1-sqs:
    template: ./lesson1-automation/ccoa-1-cfn.yml
  lesson2-cfn-nag:
    # Create buildspec.yml, cfn-nag-pipeline.yml, volume.yml and zip to ccoa-workshop/2
    parameters:
      CodeCommitS3Bucket: 'ccoa-workshop'
      CodeCommitS3Key: 'lesson2-preventive/ccoa-2-examples.zip'
    template: ./lesson2-preventive/cfn-nag-pipeline.yml
  lesson6-continuous:
    parameters:
      CodeCommitS3Bucket: 'ccoa-workshop'
      CodeCommitS3Key: 'lesson6-continuous/ccoa-lesson6-examples.zip'
    template: ./lesson6-continuous/ccoa-6-pipeline.yml
    
    
    