project:
  name: ccoa
  regions:
    - us-east-1
tests:
  lesson1-sqs:
    template: ./lesson1-automation/ccoa-1-cfn.yml
  lesson2-cfn-nag:
    parameters:
      CodeCommitS3Bucket: ccoa-workshop
      CodeCommitS3Key: ccoa-2-examples.zip
    template: ./lesson2-preventive/cfn-nag-pipeline.yml
  lesson5-remediation:
    template: ./lesson5-remediation/ec2-eip-remediation.yml
  lesson6-continuous:
    parameters:
      CodeCommitS3Bucket: ccoa-workshop
      CodeCommitS3Key: ccoa-lesson6-examples.zip
    template: ./lesson6-continuous/ccoa-6-pipeline.yml
