version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
      - 'curl -O https://bootstrap.pypa.io/get-pip.py'
      - python3 get-pip.py
      - pip install --upgrade pip
      - pip3 install taskcat
  build:
    commands:
      - echo Build started on `date`
      - aws s3 sync ./lesson2-preventive/ccoa-2-examples.zip s3://ccoa-workshop/5
      - taskcat -d test run --lint-disable
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
