version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  build:
    commands:
      - echo In buildspec-setup.yml Build started on `date`
      - aws s3 sync . s3://ccoa-workshop
      - cd lesson2-preventive
      - zip ccoa-2-examples.zip *.*
      - aws s3 sync . s3://ccoa-workshop
      - cd ../lesson6-continuous
      - zip ccoa-lesson6-examples.zip *.*
      - aws s3 sync . s3://ccoa-workshop
  post_build:
    commands:
      - echo In buildspec-setup.yml Build completed on `date`
artifacts:
  files:
    - '**/*'
