version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  build:
    commands:
      - echo In buildspec-setup.yml Build started on `date`
  post_build:
    commands:
      - echo In buildspec-setup.yml Build completed on `date`
