version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python3 get-pip.py
      - pip install --upgrade pip
      - pip3 install taskcat
  build:
    commands:
      - echo Build started on `date`
      - taskcat test run
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'