version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  build:
    commands:
      - echo In buildspec-setup.yml Build started on `date`
      - cd lesson2-preventive
      - zip ccoa-2-examples.zip *.*
  post_build:
    commands:
      - echo In buildspec-setup.yml Build completed on `date`
artifacts:
  files:
    - '**/*'