
AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  MyDB: 
    Type: "AWS::RDS::DBInstance"
    Properties: 
      AllocatedStorage: "100"
      DBInstanceClass: db.t3.small
      Engine: MySQL
      EngineVersion: "5.7.22"
      Iops: "1000"
      MasterUserPassword: "password"
      MasterUsername: "username"